apiVersion: apps/v1
kind: Deployment
metadata:
  name: tivoku-web
  namespace: personal
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: tivoku-web
  template:
    metadata:
      labels:
        app: tivoku-web
    spec:
      containers:
        - name: tivoku-web
          image: ghcr.io/niro58/tivoku-web:88dbdba3bd7e54cd85f0a86827733363d4c52077
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 25m
              memory: 250Mi
            limits:
              cpu: 100m
              memory: 450Mi
          env:
            - name: PUBLIC_MODE
              value: prod
